In [ ]:
a=[i for i in range(10)]
print(a)
import numpy as np

#to create array
#np.array9to convert list into array)
#np.zero/np.ones(to create identity)
#
#np.linspace(1,1000,100)it makes the linear by equalling space
#properties
#arr.shape(to check the space of the array)
#arr.size(to check the element of the array)
#arr.ndim("it gives the number of dimension")
#to access the array we must know indexing we can index by the square bracket
#slicing method for eg A[1:5](it also doesnt include the last element) if it is [::](it gives all the elements) if it is[::-1] it reverse all the elements
#for multidimensional we must give the row and column A=[1,1]
#A=[:5,5:] it indicates the row and column
#arr.reshape()(it reshape the array according to our needs)
#matrix multiplication=np.dot(A,B), A@B iy also multiply, np.matmul(A,B) it doesnt multiply the vector
a=np.array((1,2,3))
b=np.array((1))
print(a+b)




[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4]


4.1
Problem - 1: Array Creation:

In [ ]:
import numpy as np

a=np.empty((2,2))#Initialize an empty array with size 2X2.
print("Empty_array:","\n",a)

one_array=np.ones((4,2))#one array with size 4X2
print("Ones array: \n", one_array)
print("Np.full: ",np.full(4,2))
#The first argument should be an array-like object
print("Zeros_like: \n",np.zeros_like(a))  # Use 'a' as a template to create a zeros array
print("Ones_like: \n",np.ones_like(one_array)) # Use 'one_array' as a template to create a ones array
new_list=[1,2,3,4]#converting to a numpy array
print("Np.array:",np.array(new_list))


Empty_array: 
 [[5.01745199e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
Ones array:  
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Np.full:  [2 2 2 2]
Zeros_like:  
 [[0. 0.]
 [0. 0.]]
Ones_like:  
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Np.array: [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
import numpy as np

print("Ranging from 10 to 49: ","\n",np.arange(10,49))# array ranging from 10 to 49

array=np.array([[0,1,2],[3,4,5],[6,7,8]])
reshaped_array=array.reshape(9,1)
print("Reshaped_array: \n",reshaped_array)

a=np.eye(3,3)
print("Identity matrix: \n", a)

random_array=np.random.random(30)
print("Random_array: \n",random_array)
mean_value=random_array.mean()
print("MeanValue: \n", mean_value)

mini_max=np.random.rand(10,10)
print("Minimum: \n",np.min(mini_max))
print("Maximum: \n",np.max(mini_max))

#Instead of np.zeros_like, use np.zeros to specify the size
zero_size=np.zeros(10) #Creating a 1-D array of 10 zeros
#If you need a 2x2 array: zero_size = np.zeros((2, 2))
#If you need a multi-dimensional array you should specify the dimensions as a tuple.


remove_element = np.zeros(10)
remove_element[4]=1
print("Removing 5th element: ", remove_element)

arr=[1,2,0,0,4,0]
print("ReversedArray: \n",arr[::-1])#it prints the reverse
print("OrginalArray: \n",arr[::])#it prints the orginal

# Define the dimensions of the array
rows = 5
cols = 6

# Create an array filled with 1s
bordered_array = np.ones((rows, cols))

# Set the inner elements to 0 using slicing
bordered_array[1:-1, 1:-1] = 0

# Print the resulting array
print("BoarderedArray: \n",bordered_array)

# Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill odd rows with 1s at even columns
checkerboard[::2, 1::2] = 1  # Fill even rows with 1s at odd columns

print("Checkerboard Pattern:")
print(checkerboard)


Ranging from 10 to 49:  
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
Reshaped_array: 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
Identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random_array: 
 [0.31746402 0.61695265 0.91939001 0.42902392 0.20876136 0.40002436
 0.79048575 0.44811867 0.91429945 0.19453723 0.46414251 0.79786329
 0.84048754 0.49080008 0.53035413 0.25693418 0.25848622 0.4936593
 0.20984374 0.59604208 0.91053527 0.68491291 0.76970857 0.8843707
 0.07807143 0.19506258 0.48494154 0.19394862 0.45743809 0.06874019]
MeanValue: 
 0.4968466794753986
Minimum: 
 0.021113488576928963
Maximum: 
 0.9782613576014505
Removing 5th element:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
ReversedArray: 
 [0, 4, 0, 0, 2, 1]
OrginalArray: 
 [1, 2, 0, 0, 4, 0]
BoarderedArray: 
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
Checkerboard Pattern:
[[0 1 0 1 0 1 0 1]


Problem - 3: Array Operations:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);
add=np.add(x,y)
print("Addition: \n",add)
sub=np.subtract(x,y)
print("Subtraction: \n",sub)
square=np.square(x)#it only takes one argument
print("Square of x: \n", square)
square1=np.square(v)
print("Square of v: \n",square1)
product1=np.dot(v,w)
print("Dot product of v and w: \n",product1)
product2=np.dot(x,y)
print("Dot product of x and y: \n",product2)
concatenate=np.concatenate((x,y))
print("Concatenation: \n",concatenate)
concatenate1=np.vstack((v,w))#it prints in a vertical line
print("Vertical_stacking: \n",concatenate1)
# concatenate2=np.concatenate((x,v))
# print("Concatenation: \n",concatenate2)
#ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has
# 2 dimension(s) and the array at index 1 has 1 dimension(s)




Addition: 
 [[ 6  8]
 [10 13]]
Subtraction: 
 [[-4 -4]
 [-4 -3]]
Square of x: 
 [[ 1  4]
 [ 9 25]]
Square of v: 
 [ 81 100]
Dot product of v and w: 
 219
Dot product of x and y: 
 [[19 22]
 [50 58]]
Concatenation: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Vertical_stacking: 
 [[ 9 10]
 [11 12]]


Problem - 4: Matrix Operations:

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
inverse=np.linalg.inv(A)
# print("Inverse of A: \n",inverse)
dotproduct=np.dot(A,inverse)
print(dotproduct)

c=np.dot(A,B)
print("AB: \n",c)
d=np.dot(B,A)
print("BA: \n",d)
print("Hence AB doesnt equal BA")

e=np.dot(A,B)
transpose1=np.transpose((e))
print("(AB)^t: \n",transpose1)

transpose2=np.transpose((A))
transpose3=np.transpose((B))
f=np.dot(transpose3,transpose2)
print("B^t.A^t: \n", f)
print("Hence prove (AB)^t = B^tA^t.")



[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB: 
 [[23 13]
 [51 29]]
BA: 
 [[36 44]
 [13 16]]
Hence AB doesnt equal BA
(AB)^t: 
 [[23 51]
 [13 29]]
B^t.A^t: 
 [[23 51]
 [13 29]]
Hence prove (AB)^t = B^tA^t.


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [ ]:
a=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
b=np.array([-1,-3,9])
A=np.linalg.inv(a)
B=np.linalg.solve(A,b)
# Define x, y, and z as numpy arrays or lists before assigning values to their elements.
x = np.zeros(1)  # Initialize x as a NumPy array with 3 elements, all initialized to 0
y = np.zeros(2)  # Initialize y as a NumPy array with 3 elements, all initialized to 0
z = np.zeros(3)  # Initialize z as a NumPy array with 3 elements, all initialized to 0
# Now you can assign values to the elements of x, y, and z
x[0] = B[0]
y[1] = B[1]
z[2] = B[2]
print(x,y,z)


[16.] [ 0. 20.] [  0.   0. -15.]
