In [1]:
import sklearn

In [2]:
sklearn.show_versions()


System:
    python: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
executable: /usr/bin/python3
   machine: Linux-6.1.85+-x86_64-with-glibc2.35

Python dependencies:
      sklearn: 1.6.0
          pip: 24.1.2
   setuptools: 75.1.0
        numpy: 1.26.4
        scipy: 1.13.1
       Cython: 3.0.11
       pandas: 2.2.2
   matplotlib: 3.8.0
       joblib: 1.4.2
threadpoolctl: 3.5.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
    num_threads: 2
         prefix: libopenblas
       filepath: /usr/local/lib/python3.10/dist-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so
        version: 0.3.23.dev
threading_layer: pthreads
   architecture: Haswell

       user_api: blas
   internal_api: openblas
    num_threads: 2
         prefix: libopenblas
       filepath: /usr/local/lib/python3.10/dist-packages/scipy.libs/libopenblasp-r0-01191904.3.27.so
        version: 0.3.27
threading_layer: pthreads
   architecture: Haswell

       user

In [3]:
import pandas as pd

In [21]:
data=pd.read_csv("/content/drive/MyDrive/diabetes.csv")
x=data.drop(columns=["BloodPressure"])
print(x.shape)

(768, 8)


In [22]:
#target vector
y=data["BloodPressure"]
print(y.shape)

(768,)


In [14]:
n_class = 2
filtered_data=data[data["BloodPressure"] < n_class]
x=filtered_data.drop(columns=["BloodPressure"])
y=filtered_data["BloodPressure"]

In [18]:
from sklearn.preprocessing import StandardScaler
data=[[0, 0], [0,0], [1,1], [1,1]]
scaler=StandardScaler()
print(scaler.fit(data))
transformed_data=scaler.transform(data)
transformed_data_direct= scaler.fit_transform(data)


StandardScaler()


In [25]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.25,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None
)


In [32]:
from sklearn.model_selection import train_test_split
import numpy as np

x = np . array ([[1 , 2] , [3 , 4] , [5 , 6] , [7 , 8] , [9 , 10]])
y = np . array ([0 , 1 , 0 , 1 , 0])
X_train , X_test , y_train , y_test = train_test_split (x , y ,
test_size =0.2 , random_state =42)
print (" X_train :", X_train )
print (" X_test :", X_test )
print (" y_train :", y_train )
print (" y_test :", y_test )

 X_train : [[ 9 10]
 [ 5  6]
 [ 1  2]
 [ 7  8]]
 X_test : [[3 4]]
 y_train : [0 0 0 1]
 y_test : [1]


In [34]:
class Estimator(object):
    def fit(self, X, y=None):
        """Fits estimator to data."""
        # Store the data to simulate learning
        self.X_ = X
        self.y_ = y
        return self

    def predict(self, X):
        """Makes predictions using the learned data."""
        # For this simple example, we are just going to return the same values from the training data
        # In a real estimator, this would involve applying a trained model to the new data X
        if not hasattr(self, "X_"):
            raise ValueError("Model has not been fitted yet.")
        return self.y_  # Returning the stored labels for

In [38]:
from sklearn . neighbors import KNeighborsClassifier
from sklearn . datasets import load_iris
from sklearn . model_selection import train_test_split
# Split data into training and testing sets
X_train , X_test , y_train , y_test = train_test_split (X , y ,
test_size =0.3 , random_state =42)
# Set hyper - parameters for the KNeighborsClassifier
clf = KNeighborsClassifier ( n_neighbors =5)
# Train the model using the training data
clf . fit ( X_train , y_train )
# Make predictions on the first 5 samples from X
print (" Predictions for the first 5 samples :", clf . predict ( X
[:5]) )
# Compute class probabilities for the first 5 samples
print (" Class probabilities for the first 5 samples :", clf .
predict_proba ( X [:5]) )

 Predictions for the first 5 samples : [90  0 74 54 40]
 Class probabilities for the first 5 samples : [[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.2 0.  0.2 0.  0.  0.4 0.  0.
  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.2 0.
  0.  0.2 0.2 0.  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.2 0.  0.6 0.  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.2 0.4 0.  0.  0.  0.  0.  0.  0.
  0.  0.2 0.  0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.2 0.  0.  0.
  0.  0.2 0.2 0.  0.  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0

In [39]:
from sklearn . neighbors import KNeighborsClassifier
from sklearn . model_selection import train_test_split
# Split data into training and testing sets
X_train , X_test , y_train , y_test = train_test_split (X , y ,
test_size =0.3 , random_state =42)
# Set hyper - parameters for the KNeighborsClassifier
clf = KNeighborsClassifier ( n_neighbors =5)

In [41]:

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.3, random_state=42)
# Set hyper-parameters for the KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Train the model using the training data
clf.fit(X_train, y_train)
clf . fit ( X_train , y_train )

KNeighborsClassifier()

In [43]:
from sklearn . neighbors import KNeighborsClassifier
from sklearn . model_selection import train_test_split
# Split data into training and testing sets
X_train , X_test , y_train , y_test = train_test_split (X , y ,
test_size =0.3 , random_state =42)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Set hyper-parameters for the KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)
#The following line was causing a syntax error and was redundant given the line above
#X_train , X_test , y_train , y_test = train_test_split (X , y , test_size =0.3 ,
# Train the model using the training data
clf.fit(X_train, y_train)
# Make predictions using the test data
predictions = clf.predict(X_test)
print(predictions)
# Compute class probabilities for the test data
probabilities = clf.predict_proba(X_test)
print("Class probabilities for the test data :", probabilities)
# Make predictions using the test data
predictions = clf . predict ( X_test )
print ( predictions )
# Compute class probabilities for the test data
probabilities = clf . predict_proba ( X_test )
print (" Class probabilities for the test data :", probabilities )

[60 64 52 64 80 82 64 66 58 80 60 62 70 60  0 52 60 50 74 58 66 68 60 44
 70 62 60 56 54 54 62 80 76 74 66 40 66 56 72  0 62 80 76  0  0 68 80 70
 74 76 64 54 70 54 60 62 74  0 58 74 72 74 46 58 70 64  0  0  0 52 46  0
 84 62  0 68 74 64 66 76 72 50 66 52 60 58 90 66 60 58 54 64  0 68 40 90
 66 50 82 60 64 62 70 74  0 52 58 50 50 60 64 74  0 84 50 64 66 64  0 64
 62 44 74 58  0 82  0 58  0 62 74 62 50 58 62  0  0 74 74  0 68  0  0 82
 52 66  0 62 56 62 62 84 46 74  0 78 74 62 70 60 70 74 56  0 50 74 58 62
 74 68 86 54 68 68 52 44 70 62 54 80 70 58 66 64 40 62 58 52 74 70 68 52
 78 58 72 50  0 52 68 72  0 58 72 58 70 68 24 64 64 72 66 76 62 60 74 60
 70 64  0 74 74 50 62 90  0 80 52 58 66 52 78]
Class probabilities for the test data : [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[60 64 52 64 80 82 64 66 58 80 60 62 70 60  0 52 60 50 74 58 66 68 60 44
 70 62 60 56 54 54 62 80 76

In [54]:
##Workshop questionssss


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df= pd.read_csv('/content/drive/MyDrive/diabetes.csv')
print("First 5 rows of the dataset:")
print(df.head())

print("\nData types of each column:")
print(df.dtypes)

print("\nMissing values in the dataset:")
print(df.isnull().sum())

print("\nSummary statistics:")
print(df.describe())


First 5 rows of the dataset:
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  

Data types of each column:
Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    fl

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix, classification_report

In [49]:
X_reg = data.drop(columns=['BloodPressure', 'Outcome'])  # All columns except BloodPressure and Outcome
y_reg = data['BloodPressure']
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)
reg_model = LinearRegression()
reg_model.fit(X_train_reg, y_train_reg)

# Predict on test set
y_pred_reg = reg_model.predict(X_test_reg)

In [51]:
# Evaluate
print("Regression Evaluation:")
print(f"Mean Squared Error (MSE): {mean_squared_error(y_test_reg, y_pred_reg)}")
print(f"R^2 Score: {r2_score(y_test_reg, y_pred_reg)}")
X_clf = data.drop(columns=['Outcome'])
y_clf = data['Outcome']
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X_clf, y_clf, test_size=0.2, random_state=42)
clf_model_logreg = LogisticRegression(max_iter=1000)
clf_model_logreg.fit(X_train_clf, y_train_clf)

y_pred_clf_logreg = clf_model_logreg.predict(X_test_clf)

Regression Evaluation:
Mean Squared Error (MSE): 408.8020357692283
R^2 Score: 0.182134664007779


In [52]:
# Evaluate
print("Logistic Regression Evaluation:")
print(f"Accuracy: {accuracy_score(y_test_clf, y_pred_clf_logreg)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test_clf, y_pred_clf_logreg)}")
print(f"Classification Report:\n{classification_report(y_test_clf, y_pred_clf_logreg)}")
clf_model_knn = KNeighborsClassifier(n_neighbors=5)
clf_model_knn.fit(X_train_clf, y_train_clf)

Logistic Regression Evaluation:
Accuracy: 0.7467532467532467
Confusion Matrix:
[[78 21]
 [18 37]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.79      0.80        99
           1       0.64      0.67      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154



KNeighborsClassifier()

In [53]:
# Predict on test set
y_pred_clf_knn = clf_model_knn.predict(X_test_clf)


In [55]:
# Evaluate
print("KNN Evaluation:")
print(f"Accuracy: {accuracy_score(y_test_clf, y_pred_clf_knn)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test_clf, y_pred_clf_knn)}")
print(f"Classification Report:\n{classification_report(y_test_clf, y_pred_clf_knn)}")

KNN Evaluation:
Accuracy: 0.6623376623376623
Confusion Matrix:
[[70 29]
 [23 32]]
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.71      0.73        99
           1       0.52      0.58      0.55        55

    accuracy                           0.66       154
   macro avg       0.64      0.64      0.64       154
weighted avg       0.67      0.66      0.67       154

